### ISSUE TITLE
testRuntime vs testRuntimeClasspath

### ISSUE THREAD

**Issue by theapache64** [SurpSG/code-lines-counter-gradle-plugin#2]
https://github.com/SurpSG/code-lines-counter-gradle-plugin/blob/619ffe87a79a8e35fee29c70f7741d4ba1871895/build.gradle#L33

Hi Sergi.

I've been reading your article about testing the gradle plugin, and I came across with this line.
Why do you use an additional `testCompile` for `kotlin`. The `test` should get it from the `implementation` right ? (like every other test)

For eg. For pure `junit` test (`test` directory), we don't have to defined additional dependency to use `kotlin` stdlib.

**Comment by theapache64** [comment]
```
sourceSets {
    functionalTests {
        ....
        compileClasspath += sourceSets.main.output + configurations.testRuntimeClasspath
        ...
    }
}
```

I changed `compileClasspath` like this. Now I don't have to defined additional dependency for `funcTest`. Is this a correct approach ? If not, How can i get the dependency available in `funcTest` without adding additional `testCompile`  ?

**Comment by SurpSG** [comment]
> ```
> sourceSets {
>     functionalTests {
>         ....
>         compileClasspath += sourceSets.main.output + configurations.testRuntimeClasspath
>         ...
>     }
> }
> ```
> 
> I changed `compileClasspath` like this. Now I don't have to defined additional dependency for `funcTest`. Is this a correct approach ? If not, How can i get the dependency available in `funcTest` without adding additional `testCompile` ?

Hi Shifar,
Looks good to me, thanks! I'll fix it soon

**Comment by SurpSG** [comment]
Hi Shifar,
I've applied your suggestion, thank you!
The fix is available on 'master' and 'chapter-2-testing' branches
