### ISSUE TITLE
Asking help for Jacoco's coverage in functional test but in Groovy (not kotlin) language

### ISSUE THREAD

**Issue by Jacopo-Inglese** [SurpSG/code-lines-counter-gradle-plugin#3]
Hi, i am a student who is trying to testing a plugin in Groovy .
It's a functionalTest plugin with spock and gradlekit functions:
I necessarily need to apply Jacoco's coverage for this testing which is linked to other groovy classes in my project: so i tried to use the plugin "pl.droidsonroids.jacoco.testkit"  in my build.gradle.
I tried to study your very good example that you written in "https://dzone.com/articles/functional-tests-gradle-plugin" which implemented a "Code lines counter plugin" with "pl.droidsonroids.jacoco.testkit" but i notice that part of the code it's only for KOTLIN .
This is very bad for me because unfortunately Groovy cannot do this important step of your example
"
.apply {
                // gradle testkit jacoco support
                File("./build/testkit/testkit-gradle.properties")
                    .copyTo(File(projectDir, "gradle.properties"))
            }
  "
Can you help me to modify my GROOVY plugin in the same way of the kotlin example of the "Code lines counter plugin"
Thanks a lot! (and truly sorry for my bad english)
Here is my functionalTest class code (very few lines):

""
package pluginTesi

import org.junit.Rule
import org.junit.rules.TemporaryFolder
import spock.lang.Specification
import org.gradle.testkit.runner.GradleRunner

import static org.gradle.testkit.runner.TaskOutcome.FAILED
import static org.gradle.testkit.runner.TaskOutcome.SUCCESS

class EsempiotesiPluginFunctionalTest extends Specification {

@Rule
TemporaryFolder testProjectDir = new TemporaryFolder()
File buildFile

def setup() {
    buildFile = testProjectDir.newFile('build.gradle')
    buildFile << """
        plugins {
          id('controllPlugin.prova')
        }
    """
}

def "testing configuration"() {
    given:
    File testFile = testProjectDir.newFile('config.properties')<<"""PRJs_RecallRisultatiNOC.txt=Assertion*,1000,f"""

    buildFile  <<"""
    prova{
        file2 = file('${testFile.getName()}')
  
    }
    """

    when:
    def result = GradleRunner.create()
            .withProjectDir(testProjectDir.root)
            .withArguments('prova')
            .withPluginClasspath()
            .build()

    then:
    result.task(":prova").outcome == SUCCESS
}
}

""

**Comment by SurpSG** [comment]
Hi, could you please provide a link to your project?
It will be much simpler to help if I operate all project files.

**Comment by Jacopo-Inglese** [comment]
First of all i really thank you for the answer!
My git-hub repository of work is this "https://github.com/SerafinoDiGiambattista/ProgettoSW/tree/Jacopo-Inglese-patchs"  ( it's a branch of  the main) .
The plugin  is inside "BuildSrc" in which there's also a second "build.gradle" only for buildSrc . This one is the build  in which i implemented the step of your example in DZone Java. 
The functionalTest that i post yesterday is inside "Tesiplugin/buildSrc/src/functionalTest/groovy/pluginTesi/EsempiotesiPluginFunctionalTest.groovy"

**Comment by SurpSG** [comment]
I've made some fixes to your project. After that I was able to run the functional test. Please, appy the patch below to your project
```
Index: Tesiplugin/buildSrc/build.gradle
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/Tesiplugin/buildSrc/build.gradle b/Tesiplugin/buildSrc/build.gradle
--- a/Tesiplugin/buildSrc/build.gradle	(revision da9f7f2aeb70b71be8b4f588099936180719a2f0)
+++ b/Tesiplugin/buildSrc/build.gradle	(date 1613847860414)
@@ -63,13 +63,14 @@
 gradlePlugin.testSourceSets(sourceSets.functionalTest)
 configurations.functionalTestImplementation.extendsFrom(configurations.testImplementation)
 
-// Add a task to run the functional tests
-tasks.register('functionalTest', Test) {
+task functionalTest(type: Test) {
+    description = 'Runs the functional tests.'
+    group = 'verification'
     testClassesDirs = sourceSets.functionalTest.output.classesDirs
     classpath = sourceSets.functionalTest.runtimeClasspath
 
- }
-
+    dependsOn += generateJacocoTestKitProperties
+}
 
 tasks.named('check') {
     // Run the functional tests as part of `check`
Index: Tesiplugin/buildSrc/src/functionalTest/groovy/pluginTesi/EsempiotesiPluginFunctionalTest.groovy
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/Tesiplugin/buildSrc/src/functionalTest/groovy/pluginTesi/EsempiotesiPluginFunctionalTest.groovy b/Tesiplugin/buildSrc/src/functionalTest/groovy/pluginTesi/EsempiotesiPluginFunctionalTest.groovy
--- a/Tesiplugin/buildSrc/src/functionalTest/groovy/pluginTesi/EsempiotesiPluginFunctionalTest.groovy	(revision da9f7f2aeb70b71be8b4f588099936180719a2f0)
+++ b/Tesiplugin/buildSrc/src/functionalTest/groovy/pluginTesi/EsempiotesiPluginFunctionalTest.groovy	(date 1613850042964)
@@ -7,8 +7,9 @@
 import org.junit.rules.TemporaryFolder
 import spock.lang.Specification
 import org.gradle.testkit.runner.GradleRunner
+import java.nio.file.Files
+import java.nio.file.Paths
 
-import static org.gradle.testkit.runner.TaskOutcome.FAILED
 import static org.gradle.testkit.runner.TaskOutcome.SUCCESS
 
 
@@ -17,6 +18,7 @@
     @Rule
     TemporaryFolder testProjectDir = new TemporaryFolder()
     File buildFile
+    private GradleRunner gradleRunner
 
     def setup() {
         buildFile = testProjectDir.newFile('build.gradle')
@@ -25,6 +27,16 @@
               id('controllPlugin.prova')
             }
         """
+
+        gradleRunner = GradleRunner.create()
+                .withPluginClasspath()
+                .withTestKitDir(testProjectDir.newFolder())
+                .withProjectDir(testProjectDir.root)
+
+        Files.copy(
+                Paths.get("./build/testkit/testkit-gradle.properties"),
+                new File(gradleRunner.projectDir, "gradle.properties").toPath()
+        )
     }
     
     
@@ -45,12 +57,7 @@
         
         
         when:
-        def result = GradleRunner.create()
-                .withProjectDir(testProjectDir.root)
-                .withArguments('prova')
-                .withPluginClasspath()
-                .build()
-
+        def result = gradleRunner.withArguments('prova').build()
 
         then:
         result.task(":prova").outcome == SUCCESS

```

**Comment by SurpSG** [comment]
If you have any additional questions then email me

**Comment by Jacopo-Inglese** [comment]
Hi Mr. Gnatiuk, first of all i want to really thank you for your help 
and your time that you dedicate me .
Thank you so much.
I would like to ask you just one think:
i put in my project all the changes you made yesterday , but i 
necessarily have to have my file EsempiotesiPluginFunctionalTest.groovy 
in the way you can see under this email because i need this part of the 
code

\\\\\\
   File testFile = 
testProjectDir.newFile('config.properties')<<"""PRJs_RecallRisultatiNOC.txt=Assertion*,1000,f"""
         buildFile  <<"""
         prova{
             file2 = file('${testFile.getName()}')

         }
\\\\\\\\\\\\\

for the correct implementation of my plugin in the whole project .

Now in this way i can see in buildSrc the Jacoco report with the command 
"Gradle jacocoTestReport" ( so the coverage problem now is solved, thank 
you :D )  but on the contrary if i use the comman "gradle build" it 
fails with this message :

\\\\\
* What went wrong:
Execution failed for task ':functionalTest'.
> Failed to create MD5 hash for file content.
\\\\\\\


I do not want in any way to commit yourself too much, and bother you too 
much
  but if in case you can give me an explanation of a possible solution 
because in StackOverFlow.com is not well specified i would be very 
grateful. If you can't, I still thank you very much for your exceptional 
help during these days.


ps : This is my actual functionalTest class.


"package pluginTesi

import org.junit.Rule
import org.junit.rules.TemporaryFolder
import spock.lang.Specification
import org.gradle.testkit.runner.GradleRunner
import java.nio.file.Files
import java.nio.file.Paths

import static org.gradle.testkit.runner.TaskOutcome.FAILED
import static org.gradle.testkit.runner.TaskOutcome.SUCCESS


class EsempiotesiPluginFunctionalTest extends Specification {

     @Rule
     TemporaryFolder testProjectDir = new TemporaryFolder()
     File buildFile
     private GradleRunner gradleRunner

     def setup() {
         buildFile = testProjectDir.newFile('build.gradle')
         buildFile << """
             plugins {
               id('controllPlugin.prova')
             }
         """
         gradleRunner = GradleRunner.create()
                 .withPluginClasspath()
                 .withProjectDir(testProjectDir.root)
                 .withTestKitDir(testProjectDir.newFolder())

         Files.copy(
                 Paths.get("./build/testkit/testkit-gradle.properties"),
                 new File(gradleRunner.projectDir, 
"gradle.properties").toPath()
         )

     }



     def "testing configuration NUMBER ONE "() {
         given:
         File testFile = 
testProjectDir.newFile('config.properties')<<"""PRJs_RecallRisultatiNOC.txt=Assertion*,1000,f"""

         buildFile  <<"""
         prova{
             file2 = file('${testFile.getName()}')

         }
         """

         when:

         def result = gradleRunner.withArguments('prova').build()
         then:
         result.task(":prova").outcome == SUCCESS
     }

"

  }

**Comment by SurpSG** [comment]
Sorry, cannot help with this. 
Please, check the next links that could help you:
* https://stackoverflow.com/questions/48632019/gradle-build-error-on-windows-failed-to-create-md5-hash-for-file/48894292
* https://github.com/detekt/detekt/issues/807
* https://stackoverflow.com/questions/59234164/gradle-repository-failed-to-create-md5-hash-for-file-content
* https://discuss.gradle.org/t/gradle-build-issue-failed-to-create-md5-hash-for-file-content/32844

**Comment by Jacopo-Inglese** [comment]
Ok,don't worry, I really thank you for all the help you gives me in this 
days!
